# Generated by Django 4.1.6 on 2023-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('gr_gallina_dia', models.IntegerField(db_column='Gr/Gallina/Dia')),
            ],
            options={
                'db_table': 'alimentacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleJornada',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('rotos', models.IntegerField()),
                ('descarte', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_regis', models.DateField()),
                ('num_ficha', models.CharField(max_length=50)),
                ('titulacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallinas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('cantidad_gallinas', models.IntegerField()),
                ('peso_promedio', models.IntegerField()),
                ('edad_sem', models.IntegerField()),
                ('procedencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gallinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galpones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_galpon', models.CharField(max_length=100)),
                ('ancho', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('area', models.IntegerField()),
                ('capac_bebed', models.IntegerField()),
                ('cant_bebed', models.IntegerField()),
                ('capac_comed', models.IntegerField()),
                ('cant_comed', models.IntegerField()),
                ('capac_gall', models.IntegerField()),
                ('cant_gall', models.IntegerField()),
                ('fecha_regis', models.DateField()),
            ],
            options={
                'db_table': 'galpones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MortalidadDescarte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cant_muertas', models.IntegerField()),
                ('cant_descarte', models.IntegerField()),
                ('saldo', models.IntegerField()),
            ],
            options={
                'db_table': 'mortalidad_descarte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'produccion_diaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_huevos', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos_huevos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=10)),
                ('celular', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('registro', models.DateField()),
                ('conexion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
