# Generated by Django 4.1.6 on 2023-04-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
