# Generated by Django 4.1.6 on 2023-05-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_jornada_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallinas',
            options={'managed': False, 'verbose_name': 'Gallina', 'verbose_name_plural': 'Gallinas'},
        ),
    ]
