# Generated by Django 4.1.6 on 2023-05-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_gallinas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
